apiVersion: kustomize.config.k8s.io/v1
kind: Values
metadata:
  name: file1
spec:
  blueGreen:
    activeService: helloworld-svc-active
    autoPromotionEnabled: false
    previewService: helloworld-svc-preview
  deploymentColor: orange
